# Generated by Django 4.0.7 on 2022-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cedula', models.CharField(max_length=10, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('correo', models.EmailField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
    ]
