# Generated by Django 4.0.7 on 2022-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_empleado_cedula_alter_empleado_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoEmpleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoEmpleado', models.CharField(max_length=100, null=True, unique=True)),
                ('sueldo', models.FloatField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Empleado',
                'verbose_name_plural': 'Tipos de Empleados',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
