# Generated by Django 4.0.7 on 2022-09-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipoempleado_rename_empleado_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=10, null=True, unique=True)),
                ('tipoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoempleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
    ]
