# Generated by Django 4.0.7 on 2022-09-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_empleado_nombre_alter_empleado_tipoempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipoEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoempleado'),
        ),
    ]
