# Generated by Django 4.0.7 on 2022-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Licor',
                'verbose_name_plural': 'Licores',
                'ordering': ['id'],
            },
        ),
    ]
