# Generated by Django 4.0.7 on 2022-09-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_licor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Licor',
            new_name='tipoLicor',
        ),
        migrations.AlterModelOptions(
            name='tipolicor',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Licor', 'verbose_name_plural': 'Tipoes de Licores'},
        ),
    ]
