# Generated by Django 4.0.7 on 2022-09-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_nombre_tipolicor_tipolicor'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DetCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField(null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('licor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.licor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
    ]
