# Generated by Django 4.0.7 on 2022-09-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_compra_fecha_alter_compra_total_detcompra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detcompra',
            options={'ordering': ['id'], 'verbose_name': 'DetCompra', 'verbose_name_plural': 'DetCompras'},
        ),
    ]
