# Generated by Django 4.0.7 on 2022-09-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_detcompra_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detcompra',
            old_name='compra',
            new_name='proveedor',
        ),
    ]
