# Generated by Django 4.0.7 on 2022-09-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_rename_compra_detcompra_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detcompra',
            old_name='proveedor',
            new_name='compra',
        ),
    ]
