# Generated by Django 4.0.7 on 2022-09-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_nombre_tipolicor_tipolicor'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField(null=True)),
                ('licor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.licor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
            options={
                'verbose_name': 'DetVenta',
                'verbose_name_plural': 'DetVentas',
                'ordering': ['id'],
            },
        ),
    ]
